# Generated by Django 5.0 on 2026-07-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('health_metricid', models.AutoField(db_column='health_metricID', primary_key=True, serialize=False)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('blood_sugar', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Health_metrics',
                'managed': False,
            },
        ),
    ]
