import sys

def fix_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    mapping = {
        'Cáº­p': 'Cập',
        'nháº­t': 'nhật',
        'Tiá»ƒu': 'Tiểu',
        'Ä‘Æ°á» ng': 'đường',
        'TrÆ°á»›c': 'Trước',
        'ngá»§': 'ngủ',
        'bá»¯a': 'bữa',
        'cáº§n': 'cần',
        'láº§n': 'lần',
        'ngÃ\xa0y': 'ngày',
        'ngÃ y': 'ngày',
        'Tim': 'Tim',
        'máº¡ch': 'mạch',
        'thÃ\xa0nh': 'thành',
        'công': 'công',
        'âœ“': '✓',
        'Ä Ã£': 'Đã',
        'Ä‘á»•i': 'đổi',
        'Huyáº¿t': 'Huyết',
        'Ã¡p': 'áp',
        'tÃ¹y': 'tùy',
        'chá» n': 'chọn',
        'gÃ¬': 'gì',
        'tháº­t': 'thật',
        'á»‘ng': 'ống',
        'KhÃ´ng': 'Không',
        'thá»ƒ': 'thể',
        'má»Ÿ': 'mở',
        'thÆ°': 'thư',
        'viá»‡n': 'viện',
        'áº£nh': 'ảnh',
        'Ä ang': 'Đang',
        'quÃ©t': 'quét',
        'toa': 'toa',
        'thuá»‘c': 'thuốc',
        'Chá» n': 'Chọn',
        'tá»«': 'từ',
        'khÃ´ng': 'không',
        'tÃªn': 'tên',
        'tÃ¬m': 'tìm',
        'tháº¥y': 'thấy',
        'thÃ´ng': 'thông',
        'tin': 'tin',
        'trong': 'trong',
        'Há»§y': 'Hủy',
        'Lá»—i': 'Lỗi',
        'khi': 'khi',
        'KhÃ¡c': 'Khác',
        'Sau': 'Sau',
        'Äƒn': 'ăn',
        'viÃªn': 'viên',
        'ThÃªm': 'Thêm',
        'Chá»‰nh': 'Chỉnh',
        'sá»a': 'sửa',
        'TÃªn': 'Tên',
        'Nháºp': 'Nhập',
        'lÃ ': 'là',
        'báº¯t': 'bắt',
        'buá»™c': 'buộc',
        'VÃ ': 'Ví',
        'dá»¥': 'dụ',
        'liá» u': 'liều',
        'lÆ°á»£ng': 'lượng',
        'Liá» u': 'Liều',
        'LÆ°u': 'Lưu',
        'Ã½': 'ý',
        'BÃ¡c': 'Bác',
        'sÄ©': 'sĩ',
        'NgÆ°á» i': 'Người',
        'kÃª': 'kê',
        'Ä‘Æ¡n': 'đơn',
        'sá»‘': 'số',
        'cÃ²n': 'còn',
        'láº¡i': 'lại',
        'Sá»‘': 'Số',
        'TÃ¡c': 'Tác',
        'dá»¥ng': 'dụng',
        'phá»¥': 'phụ',
        'Báº£o': 'Bảo',
        'quáº£n': 'quản',
        'Thá» i': 'Thời',
        'gian': 'gian',
        'uá»‘ng': 'uống',
        'Lá»‹ch': 'Lịch',
        'NgÃ y': 'Ngày',
        'báº¯t': 'bắt',
        'Ä‘áº§u': 'đầu',
        'káº¿t': 'kết',
        'thÃºc': 'thúc',
        'giá» ': 'giờ',
        'XÃ³a': 'Xóa',
        'thÃ nh': 'thành',
        'cÃ´ng': 'công',
        'Cáºp': 'Cập',
        'nháºt': 'nhật',
        'Â·': '·',
        'Ä‘Ã£': 'đã',
        'Bá» ': 'Bỏ',
        'qua': 'qua',
        'Náº¿u': 'Nếu',
        'cÃ³': 'có',
        'biáº¿t': 'biết',
        'Ä‘á»ƒ': 'để',
        'trá»‘ng': 'trống',
        'Ä‘Ã³ng': 'đóng',
        'gÃ³i': 'gói',
        'Ä‘Æ°á»£c': 'được',
        'LÆ°u': 'Lưu',
        'láº¡i': 'lại',
        'TÃ¹y': 'Tùy',
        'chá» n': 'chọn',
        'cá»§a': 'của',
        'báº¡n': 'bạn',
        'tháº¥t': 'thất',
        'báº¡i': 'bại',
        'vui': 'vui',
        'lÃ²ng': 'lòng',
        'thá»\xad': 'thử',
        'láº¡i': 'lại',
        'hÃ£y': 'hãy',
        'kiá»ƒm': 'kiểm',
        'tra': 'tra',
        'máº¡ng': 'mạng',
        'xáº£y': 'xảy',
        'ra': 'ra',
        'thá» ': 'thử',
        'lÃºc': 'lúc',
        'khÃ¡c': 'khác',
        'Ä‘Ãºng': 'đúng',
        'Ä‘á»‹nh': 'định',
        'dáº¡ng': 'dạng',
        'Vui': 'Vui',
        'LÃ²ng': 'Lòng',
        'lÆ°u': 'lưu',
        'ThÃ´ng': 'Thông',
        'Â': '',
        'â€¢': '•',
        'â€“': '–',
        'â€œ': '“',
        'â€\x9d': '”',
        'Ã³m': 'óm',
    }
    
    for k, v in mapping.items():
        content = content.replace(k, v)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

fix_file(r'c:\duan\CLONE\health_monitoring\health_monitoring_app\lib\utils\medication_dialog_helper.dart')
