# Generated by Django 5.0 on 2026-07-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(db_column='notificationID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000, null=True)),
                ('message', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationDetail',
            fields=[
                ('notification_detailid', models.AutoField(db_column='notification_detailID', primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Notification_detail',
                'managed': False,
            },
        ),
    ]
