# Generated by Django 5.0 on 2026-07-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.AutoField(db_column='appointmentID', primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('note', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
            ],
            options={
                'db_table': 'Appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('medical_documentid', models.AutoField(db_column='medical_documentID', primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('file_url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('upload_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Medical_document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medicationid', models.AutoField(db_column='medicationID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dosage', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('instruction', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
            ],
            options={
                'db_table': 'Medication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('medication_scheduleid', models.AutoField(db_column='medication_scheduleID', primary_key=True, serialize=False)),
                ('time', models.TimeField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Medication_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('imageid', models.AutoField(db_column='imageID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('file_url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('upload_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Upload_image',
                'managed': False,
            },
        ),
    ]
