# Generated by Django 5.0 on 2026-07-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.AutoField(db_column='accountID', primary_key=True, serialize=False)),
                ('usename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, unique=True)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('role', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('caregiverid', models.AutoField(db_column='caregiverID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, unique=True)),
                ('phone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Caregiver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaregiverElderly',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Caregiver_elderly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elderly',
            fields=[
                ('elderlyid', models.AutoField(db_column='elderlyID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('date_of_birthday', models.DateField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('qr_token', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('qr_expired_at', models.DateTimeField(blank=True, null=True)),
                ('medical_note', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
            ],
            options={
                'db_table': 'Elderly',
                'managed': False,
            },
        ),
    ]
