# Generated by Django 5.0 on 2026-07-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentHistory',
            fields=[
                ('treatment_historyid', models.AutoField(db_column='treatment_historyID', primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Chẩn đoán bệnh', max_length=500, null=True)),
                ('treatment', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Phương pháp / tên điều trị', max_length=500, null=True)),
                ('treatment_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Nội trú / Ngoại trú / Phẫu thuật / Theo dõi', max_length=100, null=True)),
                ('doctor_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Tên bác sĩ điều trị', max_length=255, null=True)),
                ('hospital', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Tên bệnh viện / cơ sở y tế', max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Ngày bắt đầu', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Ngày kết thúc', null=True)),
                ('result', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Kết quả điều trị', null=True)),
                ('notes', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Ghi chú thêm', null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='ongoing | completed | cancelled', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Treatment_history',
                'ordering': ['-start_date'],
                'managed': False,
            },
        ),
    ]
