# Generated by Django 5.0 on 2026-07-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checklistid', models.AutoField(db_column='checklistID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Tiêu đề checklist', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Checklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('checklist_itemid', models.AutoField(db_column='checklist_itemID', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Nội dung công việc', max_length=255, null=True)),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('note', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Ghi chú thêm', null=True)),
            ],
            options={
                'db_table': 'Checklist_item',
                'managed': False,
            },
        ),
    ]
